import { StyleSheet } from "react-native";

const css = StyleSheet.create({
    screen: {
        backgroundColor: '#fcfcfc',
        flex: 1,
        alignContent: 'center',
    },
    scrollview: {
        backgroundColor: '#fcfcfc',
      },
    logo: {
        width: 350,
        left: 25,
        right: -70,
        height: 160,
        marginTop: 30,
    },
    textinput: {
        marginTop: 15,
        borderRadius: 8,
        width: 375,
        marginLeft: 10,
        borderColor: '#ccc',
        borderWidth: 2,
        padding: 6,
        color: '#333',
    },
    datNasc: {
        marginTop: 15,
        borderRadius: 8,
        width: 180,
        marginLeft: 10,
        borderColor: '#ccc',
        borderWidth: 2,
        padding: 6,
        color: '#333',
    },
    sexo: {
        marginTop: -43,
        borderRadius: 8,
        width: 185,
        marginLeft: 200,
        borderColor: '#ccc',
        borderWidth: 2,
        padding: 6,
        color: '#333',
    },
    contBanc: {
        marginTop: 15,
        borderRadius: 8,
        width: 180,
        marginLeft: 10,
        borderColor: '#ccc',
        borderWidth: 2,
        padding: 6,
        color: '#333',
    },
    Pix: {
        marginTop: -43,
        borderRadius: 8,
        width: 185,
        marginLeft: 200,
        borderColor: '#ccc',
        borderWidth: 2,
        padding: 6,
        color: '#333',
    },
    telefone: {
        marginTop: 15,
        borderRadius: 8,
        width: 375,
        marginLeft: 10,
        borderColor: '#ccc',
        borderWidth: 2,
        padding: 6,
        color: '#333',
    },
    
    historia: {
        marginTop: 15,
        borderRadius: 8,
        width: 375,
        height: 150,
        marginLeft: 10,
        borderColor: '#ccc',
        borderWidth: 2,
        padding: 6,
        color: '#333',
    },
    texto1: {
        marginTop: 25,
        textAlign: 'center',
        color: '#333',
        fontWeight: 'bold',
    },
    texto2: {
        marginTop: 20,
        marginLeft: 10,
        color: '#333',
    },
    rua: {
        marginTop: 15,
        borderRadius: 8,
        width: 270,
        marginLeft: 10,
        borderColor: '#ccc',
        borderWidth: 2,
        padding: 6,
        color: '#333',
    },
    numero: {
        marginTop: -44,
        borderRadius: 8,
        width: 100,
        marginLeft: 285,
        borderColor: '#ccc',
        borderWidth: 2,
        padding: 6,
        color: '#333',
    },
    cidade: {
        marginTop: 15,
        borderRadius: 8,
        width: 270,
        marginLeft: 10,
        borderColor: '#ccc',
        borderWidth: 2,
        padding: 6,
        color: '#333',
    },
    estado: {
        marginTop: -44,
        borderRadius: 8,
        width: 100,
        marginLeft: 285,
        borderColor: '#ccc',
        borderWidth: 2,
        padding: 6,
        color: '#333',
    },
    btnCadastro: {
        width: 300,
        height: 42,
        backgroundColor: '#086b90',
        marginTop: 25,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 50,
        color: '#fff'
    },
    txtButton: {
        fontSize: 16,
        color: '#fff'
    },
    texto: {
        marginTop: 30,
        textAlign: 'center',
        color: '#333',
    },
    
    termoUso: {
        color: '#333',
        marginTop: 26,
        textAlign: 'center',
        fontSize: 12,
    },
    txtCopy: {
        marginTop: 13,
        textAlign: 'center',
        color: '#333',
    },

    link: {
        color: '#333',
        fontWeight: 'bold',
        marginTop: 20,
        textAlign: 'center',
        fontSize: 12,
    },
});

export { css };